export const ADD_BOOK_SUGGESTIONS = 'ADD_BOOK_SUGGESTIONS';
export const ADD_BOOKS = 'ADD_BOOKS';
export const ADD_CURRENT_BOOK_INFO = 'ADD_CURRENT_BOOK_INFO';
export const SET_SEARCH_PARAMETER = 'SET_SEARCH_PARAMETER';
export const SET_STATUS_SHOWN = 'SET_STATUS_SHOWN';
export const SET_CURR_VALUE = 'SET_CURR_VALUE';
export const SET_MESSAGE = 'SET_MESSAGE';
export const RESET_CURRENT_BOOK_INFO = 'RESET_CURRENT_BOOK_INFO';
export const RESET_BOOK_SUGGESTIONS = 'RESET_BOOK_SUGGESTIONS';

